### ISSUE TITLE
Question: Whats the type of pool

### ISSUE THREAD

**Issue by alenpaulvarghese** [OpenByteDev/deadpool-fantoccini#1]
I am having hard time figuring out the type of pool. I was trying to add pool as an attribute in the below struct.
```
struct Worker {
    worker_count: u8,
    browser_pool: Pool<Manager<Client>>,
    receiver: Receiver<Request>,
}
```
How can we annotate the type of fantoccini browser pool?

**Comment by OpenByteDev** [comment]
Have a look at the [`Pool`](https://docs.rs/deadpool-fantoccini/0.2.5/deadpool_fantoccini/type.Pool.html) type alias.
